# Generated by Django 2.0.13 on 2019-06-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('idAgenda', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='HoraMedica',
            fields=[
                ('idHora', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('rut', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('dv', models.CharField(max_length=1)),
                ('nombreCompleto', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=9)),
                ('correo', models.EmailField(max_length=254)),
                ('tipoUsuario', models.CharField(choices=[('PACIENTE', 'PACIENTE'), ('SECRETARIA', 'SECRETARIA'), ('MEDICO', 'MEDICO')], max_length=20)),
                ('especialidad', models.CharField(choices=[('MEDICINA INTERNA', 'MEDICINA INTERNA'), ('CIRUGIA GENERAL', 'CIRUGIA GENERAL'), ('PEDIATRIA', 'PEDIATRIA')], max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('rut', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('dv', models.CharField(max_length=1)),
                ('nombreCompleto', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=9)),
                ('tipoUsuario', models.CharField(choices=[('PACIENTE', 'PACIENTE'), ('SECRETARIA', 'SECRETARIA'), ('MEDICO', 'MEDICO')], max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('rut', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('dv', models.CharField(max_length=1)),
                ('nombreCompleto', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=9)),
                ('tipoUsuario', models.CharField(choices=[('PACIENTE', 'PACIENTE'), ('SECRETARIA', 'SECRETARIA'), ('MEDICO', 'MEDICO')], max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='horamedica',
            name='medico',
            field=models.ManyToManyField(to='clinica.Medico'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='horas',
            field=models.ManyToManyField(to='clinica.HoraMedica'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='medico',
            field=models.ManyToManyField(to='clinica.Medico'),
        ),
    ]
