# Generated by Django 2.0.13 on 2019-06-05 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='correo',
        ),
    ]
